const dataProducts = [
  {
    id: 1,
    imgSrc: "./assets/imgs/1-600x600.jpg",
    name: "placerat vestibulum",
    pirce: "50.000",
    data: "movers",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 2,
    imgSrc: "./assets/imgs/2-600x600.jpg",
    name: "hendrerit est",
    pirce: "74.000",
    data: "familyes",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 3,
    imgSrc: "./assets/imgs/3-600x600.jpg",
    name: "commodo augue nisi",
    pirce: "74.000",
    data: "familyes",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 4,
    imgSrc: "./assets/imgs/4-600x600.jpg",
    name: "eget sagittis",
    pirce: "74.000",
    data: "movers",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 5,
    imgSrc: "./assets/imgs/5-600x600.jpg",
    name: "massa massa",
    pirce: "74.000",
    data: "movers",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 6,
    imgSrc: "./assets/imgs/6-600x600.jpg",
    name: "sapien libero",
    pirce: "74.000",
    data: "movers",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 7,
    imgSrc: "./assets/imgs/7-600x600.jpg",
    name: "adipiscing cursus",
    pirce: "74.000",
    data: "movers",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 8,
    imgSrc: "./assets/imgs/8-600x600.jpg",
    name: "gravida semper",
    pirce: "74.000",
    data: "movers",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 9,
    imgSrc: "./assets/imgs/9-600x600.jpg",
    name: "Morbi ornare",
    pirce: "69.000",
    data: "outdoor",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 10,
    imgSrc: "./assets/imgs/10-600x600.jpg",
    name: "vulputate rutrum",
    pirce: "74.000",
    data: "outdoor",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 11,
    imgSrc: "./assets/imgs/11-600x600.jpg",
    name: "tristique auctor",
    pirce: "74.000",
    data: "outdoor",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 12,
    imgSrc: "./assets/imgs/12-600x600.jpg",
    name: "fringilla augue",
    pirce: "74.000",
    data: "familyes",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 13,
    imgSrc: "./assets/imgs/13-600x600.jpg",
    name: "adipiscing elit",
    pirce: "69.000",
    data: "familyes",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 14,
    imgSrc: "./assets/imgs/15-600x600.jpg",
    name: "Porro Cook",
    pirce: "69.000",
    data: "familyes",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 15,
    imgSrc: "./assets/imgs/16-600x600.jpg",
    name: "Duis pulvinar cook",
    pirce: "69.000",
    data: "familyes",
    sale: false,
    pirceSale: "0",
  },
  {
    id: 16,
    imgSrc: "./assets/imgs/18-600x600.jpg",
    name: "Donec eu cook",
    pirce: "69.000",
    data: "familyes",
    sale: false,
    pirceSale: "0",
  },
];
